### ISSUE TITLE
HW06: Некорректный результат на атомах

### ISSUE THREAD

**Issue by kajigor** [Glebanister/prolog-with-parsec#1]
[ta01.txt](https://github.com/Glebanister/prolog-with-parsec/files/5389833/ta01.txt)
[ta02.txt](https://github.com/Glebanister/prolog-with-parsec/files/5389834/ta02.txt)

Это два разных атома, которые парсятся в одно и то же: 

```
├─ Atom
│ ├─ Identifier: 'a'
│ ├─ AtomSequence
│ │ ├─ Atom
│ │ │ ├─ Identifier: 'b'
│ │ │ ├─ AtomSequence
│ │ │ │ ├─ Atom
│ │ │ │ │ ├─ Identifier: 'c'
│ │ │ │ │ ├─ AtomSequence

```

**Comment by Glebanister** [comment]
Fixed
